#!/usr/bin/env python
"""The Metronet IESS Online bridge."""

import logging
import json
import requests
import re
from bs4 import BeautifulSoup
import difflib
from tvchannellist import ChannelList

_LOGGER = logging.getLogger()


def set_logging(debug):
    """Set logging."""
    level = logging.INFO
    if debug:
        level = logging.DEBUG

    console = logging.StreamHandler()
    console.setLevel(level)
    formatter = logging.Formatter(
        "%(asctime)s %(name)-12s: %(levelname)-8s %(message)s", "%Y-%m-%d %H:%M:%S"
    )
    console.setFormatter(formatter)

    _LOGGER.addHandler(console)
    _LOGGER.setLevel(logging.DEBUG)


def main():
    cl = ChannelList("us", 10001)
    providers = cl.get_providers()
    print(providers)
    if providers:
        cl.set_provider(providers[1])
    cl.load_channels()
    print(cl.engine.lookup)
    print(cl.get_channel("espn"))
    print(cl.get_channel("wcbs", True))


if __name__ == "__main__":
    main()
